### ISSUE TITLE
base64 is bigger than 32k

### ISSUE THREAD

**Issue by aracila** [szimek/signature_pad#107]
Hi, 
First of all thank you very much for such a great tool!
The only library I was able implement in my APEX application which is working on both mobile and desktop / touch and non touch devises. 

The only issue I've got is that base64 string on mobile devices is getting way to big.
It is happening only on phones and tablets, I think because of hi res, but basically signaturePad.toDataURL() is generating a string more than 32k, and APEX isn't very good at handling this kind of sizes. 

I did dig into many threads how to re-size the canvas image but they are not really working with your library, maybe because, being DB Developer and not js I just don't know how to implement it right. 
For example on my Nexus 5 the canvas get almost full screen, and there is no point in storing 1080 x 1920 signature in database. 
The Ideal would be to have an option to re-size the canvas before puling the base64 string, and embed this functionality into the library itself, something like: signaturePad.toDataURL(300,100).
Which would re-size the image to 300X100px and after that generate base64 string.

I hope for professionals like you it would be a quick improvement, I am desperate as i have spend all weekend and still no result :(

Thank a lot,
Andrei

**Comment by szimek** [comment]
So the issue is that you can't store strings longer than 32KB in your database? Do you have to store it in a database, can't you save it and store it as a file?

Anyway, you should be able to implement image resizing locally relatively easy. Create a new image and set the base64 string as its source (`var image = new Image(); image.src = <base64>;`) Create a new canvas of desired size and draw this image onto it. Check out the second form of [`drawImage`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) method - it allows you to scale source image. Once you got the scaled image on the canvas, you can read it back using `toDataURL` and send it to the server.

**Comment by aracila** [comment]
Thank you so much for explanations and link. I was digging in same solution entire weekend but some how everyone just pasted peaces of code without explaining and linking to some documentation. 
Solution if some one will be interested:
   var temp_image = new Image(); temp_image.src = signaturePad.toDataURL();
   var tempCanvas = document.createElement('canvas');
   tempCanvas.width = 300;
   tempCanvas.height = 100;
   tempCanvas.getContext('2d').drawImage(temp_image, 0, 0, 300, 100);
   alert( tempCanvas.toDataURL().length);
