### ISSUE TITLE
Performance on Android Webview

### ISSUE THREAD

**Issue by travoux** [szimek/signature_pad#113]
Excellent and it became really handy. 
I had an issue with the performance when it was loaded inside Android Webview. the drawing became really slow.. anything to boost the performance?

**Comment by szimek** [comment]
Not at the moment, but I'll try to take a look at it when I have some time. Which version of Android are you talking about?

**Comment by arthurzaczek** [comment]
I have a Android 4.4.2 tablet with that performance issue. An Android Update is not possible. Anything I can help with debugging that issue?

**Comment by Lonzak** [comment]
That is strange since with Android 4.4 the old webview was replaced with a much more improved version (chrome based).
https://developer.chrome.com/multidevice/webview/overview
There was an aditional update in 4.4.3 so you are only missing a minor version :-/

We did improve the performance by drawing lines (instead of Bezier curves) for points which are quite close to each other. The greater the distance of those (line connecting points) the better the performance (but the worse the quality)...

**Comment by travoux** [comment]
Sorry for the late response. The performance is OK now. It was quite a while so I can't really recall how it it got better.. :)

**Comment by FallenRiteMonk** [comment]
I have exactly this problem.
I am on android 4.4.2 (no chance of updating) and it has to run on this exact device.

I am running this in an ionic app and noticed that the main problem lies on starting to draw on the canvas. Meaning if I start drawing right away it nearly doesn't work at all, but if i put my pen on the screen, wait a moment, and then start drawing it works almost fine.

Any ideas how I could fix this problem?

**Comment by szimek** [comment]
I don't even own a device with Android 4.x, so someone would have to do some profiling on this device and see where the problem is exactly.

There are probably some relatively easy optimizations e.g. currently it calculates and draws Bezier curves even for points close to each other, but it's always better to profile than guess.

I plan to modify the algorithm to reduce number of points and draw simpler curves, but because of lack of free time, it's not something that will happen anytime soon. Also, I don't know if it's going to be any faster ;)

**Comment by FallenRiteMonk** [comment]
Well I would be willing to help debug the issue.
What exactly would you want me to do?

**Comment by UziTech** [comment]
closing as stale
