### ISSUE TITLE
problem with egde browser and touchdevices

### ISSUE THREAD

**Issue by dideldum73** [szimek/signature_pad#134]
First of all thank you very much for your great work.

Unfortunately i have a problem running the pad on Microsofts edge browser (comes with Windows 10) and touch devices. After touching, i draws the first dot and after this the movement of the finger ist moving the whole page (scrolling), no more "drawing" inside the pad. With IE 11 or firefox i have no problems... 

Any idea or workaround for me ? For a project i am using the webview control from visual studio and since version 2015 this control is based on edge browser..

Thanks

**Comment by szimek** [comment]
There's some IE specific code in signature pad at [src/signature_pad.js#L147](https://github.com/szimek/signature_pad/blob/master/src/signature_pad.js#L147) and it looks like since IE11 it shouldn't have `ms` prefix... You can try to remove the `ms` prefix (`style.touchAction`) and see if it helps. You can find more info about this property [here](https://msdn.microsoft.com/en-us/library/windows/apps/hh767313.aspx).

I'll try to check it out in BrowserStack, but I'm not sure if I can emulate there a touch device for Edge browser.

**Comment by dideldum73** [comment]
thanks for the fast reply. removing the `ms` prefix didn't help, but adding `touch-action: none;` directly into the css resolved the issue for me, thank you very much ! If you want me to test something on Egde with touch, feel free to contact me.

**Comment by szimek** [comment]
@dideldum73 If you just change the line mentioned before to 
```javascript
this._canvas.style.touchAction = 'none';
```
it doesn't help? In Chrome it adds `style="touch-action: none;"` attribute to the element, so I suppose it should have the same effect as adding it directly to CSS and would be much better solution than asking people to add some custom CSS...

I'd be grateful if you could check again and let me know if it works with setting touch action from JS.

**Comment by dideldum73** [comment]
you're right, it perfectly works with your line above. not sure, what mistake i made this morning while trying, probably i used a small a in `touchAction`. Thank you very much for your help.

**Comment by szimek** [comment]
Thanks for confirming it! I'll add it to the repo then.
