### ISSUE TITLE
PNG Alpha

### ISSUE THREAD

**Issue by daryltomkins** [szimek/signature_pad#18]
Hello, When saving the signature pad as a PNG file using PHP we have noticed it gets saved in Alpha Channel format, however our application requires a non-Alpha PNG file.  Is there anything we can change in the signature pad javascript or canvas that would stop it from being saved as Alpha? Thanks, Daryl Tomkins.

**Comment by acs306** [comment]
@szimek I'm not sure how much this is maintained since it's been 10 years since this was posted.... but, I'm having the same issue daryl reported. I am storing the PNG image in an oracle database as a blob then using that blob in [PLPDF](https://plpdf.com/) which does not allow an alpha channel in the PNGs that are used in a PDF. I tried setting the background color to white in the instantiation of my SignaturePad object, but, that is not working as expected, as, I still get an error from PLPDF that alpha channel is not allowed.

**Comment by UziTech** [comment]
Signature pad uses the canvas [`toDataURL`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) method to create the png. There isn't much we can do in signature pad to change the output of that method.
