### ISSUE TITLE
Reading an Signature Image as the screen orientation changes and write it back on canvas after resizing it

### ISSUE THREAD

**Issue by chinmaydalvi** [szimek/signature_pad#194]
In Mobile devices How we can read the image as the screen orientation changes and write it back to 
modified Canvas. As the screen orientation changes height and width changes of the canvas and signature pad automatically clears.
So this is not good behavior as for  Mobile devices screen orientation continuously changes.

**Comment by maxshuty** [comment]
I am having a similar issue. One work around you can do is to create a second canvas element that is not displayed then draw what's on the current canvas onto the hidden one. After the resize redraw what's on the hidden canvas onto the "real" one. It works fine with a minor issue of the hit point's getting messed up. I'm still working through that bit and I'll try and post an update here once I've got that sorted out. 
By design, `canvas` elements clear when their `width` or `height` change.

`<canvas id="buffer" style="display:none;></canvas>`

Next:

`function resizeCanvas() {
        var ratio = Math.max(window.devicePixelRatio || 1, 1);
        var w = canvas.offsetWidth * ratio;
        var h = canvas.offsetHeight * ratio;
        buffer.width = w;
        buffer.height = h;
        buffer.getContext('2d').drawImage(canvas, 0, 0);
        canvas.width = w;
        canvas.height = h;

        var ctx = canvas.getContext('2d');
              ctx.scale(ratio / 2, ratio / 2);
              ctx.drawImage(buffer, 0, 0);
 }`

The problem now is that your hit point will be off. You could still have someone sign and when you change the orientation it wont lose the signature. I'm still trying to work on getting the hit points to the correct positions on resize.

**Comment by shawe** [comment]
Maybe this helps: https://github.com/szimek/signature_pad/issues/33#issuecomment-298242020
