### ISSUE TITLE
Integration with ePad or Topaz?

### ISSUE THREAD

**Issue by elemental21** [szimek/signature_pad#196]
I'm sure I know the answer, but it would appear there isn't any integration/planned integration with ePad or Topaz signature pads correct?

**Comment by szimek** [comment]
What would you expect from such integration? I've never used these tools, so I really don't know anything about them.

**Comment by elemental21** [comment]
In this case the expectation would be that the topaz and ePad device input would be captured in the signature_pad canvas component.  Essentially exactly how it is now except being able to interface with the hardware signature pads as well as mouse driven input.

Here's the SDKs for each of them:
http://www.epadsupport.com/getlatest/ePad-visionSDK_ChromeFirefox_IntegrationGuide.pdf
http://www.topazsystems.com/sigweb.html

**Comment by szimek** [comment]
I haven't read the docs yet, but I'm working (very slowly, due to lack of free time :/) on a version of this library that will give access to all drawn points and also allow to pass such list of points to draw a signature.

This could make such integration possible - you could get a list of points (or whatever they actually provide) from these devices and map them to a format that this library can understand.

If you'd like to play with it yourself without waiting for me, here's the branch with the new version: https://github.com/szimek/signature_pad/tree/draw-signature-from-point-data.

**Comment by elemental21** [comment]
Ok thanks for the heads up!
