### ISSUE TITLE
"window.onresize = resizeCanvas" in signature_pad/example/js/app.js

### ISSUE THREAD

**Issue by jbnv** [szimek/signature_pad#210]
I reported in #155 that was having an issue with the signature spontaneously disappearing on a mobile device. I tracked the issue down the "window.onresize = resizeCanvas" statement in the project's code. I found that our developer had copied and pasted the code from signature_pad/example/js/app.js into our code. 

Apparently this event gets triggered frequently on mobile devices. I observed it changing orientation, hitting the bottom of the page and other cases. I was able to reproduce it on the desktop by resizing the window.

Is there a reason that this statement is in your example? I'm removing it from our production code because this is a major issue. But I want to make sure that I am not introducing another bug in the process.

**Comment by szimek** [comment]
It's an example that shouldn't be copied 1 to 1 to production code 😉 In general it's used to show one of ways of handling canvas when screen size changes and canvas size changes as well.

If you only use it on mobile devices you can listen for orientation change instead that will allow you to handle both horizontal and vertical orientations (in this case it's best to allow only one orientation, e.g. horizontal, save image locally when the orientation changes and restore it when orientation changes back). 

If you also have a desktop version and need to use window.resize, you could throttle resize handler, so that it's not called so often.

There are plenty of ways to handle it and the one is example is just one of them.

**Comment by szimek** [comment]
I'm closing it. If you have any more questions, feel free to reopen it.
