### ISSUE TITLE
crop toDataURL('image/svg+xml');

### ISSUE THREAD

**Issue by chitgoks** [szimek/signature_pad#217]
hi. while ive read posts on how to crop canvas, its output is base 64 png. and yes, not everyone has access to the server so doing the trimming client side would definitely be helpful.

would like to request to have a crop for base 64 svg. svg is still best for output because it is vector.

**Comment by chitgoks** [comment]
bump. this is a very useful feature. ^_^

i hope this feature gets some interest

**Comment by sebastianfast** [comment]
Three years in and not even a reply. Bump

**Comment by vipertecpro** [comment]
> 
> 
> Three years in and not even a reply. Bump

Alright this made me emotional and want to close this issue once and for all . Will be back with solution. happy Coding.

**Comment by szimek** [comment]
PRs are welcome, though if this cropping code could be implemented as a separate library or as a separate function that can doesn't have to imported if it's not used, that would be preferable to avoid bloating this library with features few people need.

Also, I'm not really maintaining this library anymore. I'll try to clean up a few things soon and update the README file with information that I'm looking for a maintainer.

**Comment by vipertecpro** [comment]
> 
> 
> PRs are welcome, though if this cropping code could be implemented as a separate library or as a separate function that can doesn't have to imported if it's not used, that would be preferable to avoid bloating this library with features few people need.
> 
> Also, I'm not really maintaining this library anymore. I'll try to clean up a few things soon and update the README file with information that I'm looking for a maintainer.

First of all I've never taken PR before and i don't know how to maintain that, i mean except GitHub few commands and extending functions, features, parameters , etc of given libraries as per requirement, i just make patches and i really don't want to mess up with what's given to us (Thank you so much for that). Some features are logical in nature and some requires external packages to be handled, i made few packages as per my clients requirement but they are not mine at all, i've mentioned everything about them, i cloned it because some owner already abandoned their packages and some requires alot of updates like comparability with  PHP, jQuery, npm, yarn versions... new syntax, etc.

So i took chance as to learn how to do that ....and still learning. I'm really not a good contributor, because that requires proper attentions on issues, making more examples with different set of features, etc. My hands are all full right now otherwise i would have. 

Again thank you for such a beautiful package.

**Comment by sebastianfast** [comment]
I am sorry that I sounded offensive. I did not intend to offend anyone. Thank you for this package, I am happily using it. What I do not like on my search for specific answers is browsing through old and open tickets that did not receive any response, so perhaps I overlooked szimeks apparent response, that he took it up as an enhancement. Again, thank you for for this package.

To anyone desperately looking up ways for cropping SVG, I found out about multiple solutions.
1. I got lucky, because I am using those signatures in fabric.js, where you can import SVG in a way that it  trims the white-space automatically. See this code snippet:

```
fabric.loadSVGFromURL(svgFilePath, () => {
  // these are your signature path elements grouped together 
    var loadedObjects = new fabric.Group(group);
  },
  function (item, object) {
    object.set("id", item.getAttribute("id"));
    group.push(object);
  }
);
```

  2, You can modify the viewBox property in your SVG xml code to only show the signature.
  3. Otherwise, if the background is blank, you could simply omit trimming any whitespace and work with the full vector-"image" of your signature. In another problem, where I include the SVG in a PDF-file, I went this way.

**Comment by UziTech** [comment]
see https://github.com/szimek/signature_pad/issues/49#issuecomment-260976909
