### ISSUE TITLE
No drawing on an Android Nexus 10

### ISSUE THREAD

**Issue by nogame77** [szimek/signature_pad#224]
I have a web app that I created that has a signature component. I'm using an Samsung Android Nexus 10 for testing purposes (client's request) and I cannot get signature_pad to draw. 

I'm having no problems on Desktop or iPads but when it comes to the Android Nexus 10, it won't draw a signature. 

I read that someone's solution was that if the signature was at the bottom of the page, the scrolling affect on a Samsung device mucked up the signature_pad and when he moved it into a modal (so the signature pad did not scroll), it worked for him. Sadly, for me, it did not.

Once my modal appears on screen, the signature pad is then drawn. Did not work.

I'm not finding too many people with this specific problem elsewhere though so any potential solutions I could test would be greatly appreciated.

**Comment by szimek** [comment]
I don't have access to Nexus 10, so it's rather hard for me to figure out what's wrong or fix it without any more info.

Can you post your code to https://jsfiddle.net/ or https://jsbin.com/?
Do you get any JS errors in devtools console?
Is your page scrollable? If it is, can you make a version that only has a canvas, which is smaller than the page, so that the page is not scrollable and check if it works then? Though I guess you already tried it with the modal...
