### ISSUE TITLE
Transparent signature saved by signature pad in few cases (29/4608)

### ISSUE THREAD

**Issue by mhassaan** [szimek/signature_pad#256]
I am facing a wierd issue which i am unable to reproduce as well but the issue has been reported several times by end users. In some cases, base 64 encoded string is saved something like this
 
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAhMAAADGCAYAAABozwKRAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAGuSURBVHhe7cEBDQAAAMKg909tDwcEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABnamvoAAHKi5GcAAAAAElFTkSuQmCC`

and this passes the client and server side validation before saving in db but when i decode the string, its a transparent image. What could possibly be the issue ? 

I have tried reproducing the issue on different devices and browsers(Chrome,Firefox,Opera,IE), works fine for me.

Below is client side code for signature handling

```
var signaturePad = new SignaturePad(document.getElementById('signature-pad'), {
    backgroundColor: 'rgba(255, 255, 255, 0)',
    penColor: 'rgb(0, 0, 0)',
});

signaturePad.removeBlanks();
var sign = signaturePad.toDataURL();
$("#e-signature").val(sign);
$('#form1').submit();
```

**Comment by godink** [comment]
I have encountered the same problem, but I was in the current bomb box to submit the incident, the implementation of var sign = signaturePad.toDataURL ();, which led to the server is transparent, behind my solution is: in the submission of the event At the beginning, execute var sign = signaturePad.toDataURL (); first store the value of signaturePad.toDataURL () and then commit it later, probably because when you execute signaturePad.toDataURL (), the current interface is The effect of any changes to the current interface will have an effect on the value of the method signaturePad.toDataURL ()

**Comment by magorismagor** [comment]
@godink So did you solve the problem by waiting for the result of signaturePad.toDataURL()? with a delay?
