### ISSUE TITLE
.toDataURL("image/svg+xml") outputs same as .toDataURL('image/png')

### ISSUE THREAD

**Issue by oshihirii** [szimek/signature_pad#258]
I am reading this:

https://github.com/szimek/signature_pad#api

It states:  

> signaturePad.toDataURL("image/svg+xml"); // save image as SVG

I [modified official jsFiddle demo](https://jsfiddle.net/rwone/enybgtqm/) so that it uses:

`.toDataURL("image/svg+xml")`

however it outputs the same data as:

`.toDataURL('image/png')` 

Chrome Version 58.0.3029.110 (64-bit)
Ubuntu 17.04

**Edit:**  I note that jsFiddle demo is using:

https://cdnjs.com/libraries/signature_pad

And that currently only contains version `1.5.3`, whereas the latest version on GitHub seems to be `2.1.1` - so that may be the cause?

**Comment by szimek** [comment]
Yeah, I assume it's because of an old version which doesn't support SVG. I don't really know how cdnjs updates packages - if it takes files from the repo like Bower or from npm registry. You can download the latest version of this library using `npm install signature_pad` and then copy & paste the code to jsfiddle.
