### ISSUE TITLE
MouseUp event is affecting other web components.

### ISSUE THREAD

**Issue by joshvanal** [szimek/signature_pad#266]
**Do you want to request a feature or report a bug?**
Bug & Feature

**What is the current behavior?**
According to the code, mouseup event is binding to the document instead of the canvas.

**What is the expected behavior?**
Mouse Up event should have the option to be bounded to the canvas or the document.

**Comment by szimek** [comment]
How exactly is it affecting other web components? 

The main problem with listening to `mouseup` event only on the canvas, is that if someone moves the mouse cursor outside of the canvas while pressing down the mouse button and then releases it, this event won't be handled, because it will be triggered outside of the canvas.

**Comment by joshvanal** [comment]
The bug is actually a misdiagnoses.

**Comment by szimek** [comment]
Can it be closed then?

**Comment by joshvanal** [comment]
Yes sir! Thanks
