### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by liamm95** [szimek/signature_pad#308]
**Do you want to request a feature or report a bug?**
Touchmove event listeners need to add { passive: true } when listeners are added. Currently in Chrome 60, it throws warnings.

**What is the expected behavior?**
Stop Chrome from throwing warning messages

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
Chrome 60, signature_pad 2.2.0

More information here:
https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

**Comment by szimek** [comment]
@liamm95 I'm on Chrome 62 (beta) and I don't get any warnings. According to the docs you linked to, the `passive: true` option should be added if event handler doesn't call `event.preventDefault`to prevent scrolling. However, in this library `touchmove` does exactly that: https://github.com/szimek/signature_pad/blob/master/src/signature_pad.js#L63-L64.

There's no `event.preventDefault` call in `touchstart` event handler - maybe that's what your browser is complaining about? In this case I think I'll just add this call, rather than make this listener passive.
