### ISSUE TITLE
Pass callback to .fromDataURL()

### ISSUE THREAD

**Issue by MartijnR** [szimek/signature_pad#340]
Since formDataURL loads an image asynchronously, it would be great if it could return a Promise. I don't think it will cause any backwards compatibility issues.

I'd be happy to create a PR if interested.

**Comment by szimek** [comment]
Good idea! However, there are 2 issues:

- `Promise` is not supported in IE, while canvas is supported by IE9+; while IE9+ is really old, it doesn't make much sense to break compatibility for such a tiny feature
- I'm currently (very, very slowly) rewriting this library in TypeScript (https://github.com/szimek/signature_pad/tree/typescript), so the code will change quite significantly...

That said, I think it would be better if `fromDataURL` accepted an optional callback function instead of returning a promise. If you create a PR, I can release a new version and then I'll port it to the TS version.

**Comment by wulfsolter** [comment]
We're still got clients on IE9+, would be a shame to break when it's easy to promisify things yourself: https://benmccormick.org/2015/12/30/es6-patterns-converting-callbacks-to-promises/

**Comment by MartijnR** [comment]
@szimek, that makes sense. I'll create a PR that adds a callback. Thanks.

**Comment by szimek** [comment]
Implemented in the `3.0.0-beta.2` release.
