### ISSUE TITLE
Signature disappear when zooming in with both fingers on Edge tablet

### ISSUE THREAD

**Issue by benag** [szimek/signature_pad#377]
After signing when the user zoom in using touch on tablet running Edge browser, the signature disappear.

**Comment by szimek** [comment]
I don't have a tablet with Edge, but I suspect you're updating size of the canvas on `resize` event. It's possible that zooming in is triggering this event and that's why the canvas is cleared. You might try to listen to [orientationchange](https://developer.mozilla.org/en-US/docs/Web/Events/orientationchange#Example) event instead, or disable zooming on the page with the canvas.

**Comment by benag** [comment]
yes i am updating canvas size on window resize why would it clear the canvas?

Thanks

**Comment by szimek** [comment]
It's how canvas element works - changing its "internal" size via `height` or `width` clears the whole thing. There are many issues about the same subject already.

The main solutions are - switch to `orientationchange` event or store content of the canvas changing canvas size in `resize` handler and then draw stored image after resizing, though it might be blurry.

**Comment by benag** [comment]
Thanks, I will go for option 3

**Comment by shalonteoh** [comment]
switched to orientation change event the pad still appear weird when sign although it doesnt clear signature anymore.

The below method works for me.

`
var cacheOrientation;

function resizeCanvas() {
  if (cacheOrientation != window.orientation) {
    cacheOrientation = window.orientation;
    var ratio = Math.max(window.devicePixelRatio || 1, 1);

    canvas.width = canvas.offsetWidth * ratio;
    canvas.height = canvas.offsetHeight * ratio;
    canvas.getContext("2d").scale(ratio, ratio);
    signaturePad.clear();
  }
}

window.onresize = resizeCanvas;
resizeCanvas();`
