### ISSUE TITLE
onBegin fires after first data point is set

### ISSUE THREAD

**Issue by pbcomm** [szimek/signature_pad#378]
_If you have a question, please ask it on [StackOverflow](https://stackoverflow.com/questions/ask?tags=javascript+signature-pad) and use `signature-pad` tag instead of creating an issue._

**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
onBegin fires after first data point is set

_If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via <https://jsfiddle.net> or similar (template: <https://jsfiddle.net/szimek/h80phxyr/>)._
Call isEmpty() in onBegin() callback should return true on first mouse/touch event

**What is the expected behavior?**
onBegin should fire before first data point is set

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
Yes

**Comment by szimek** [comment]
Hey @pbcomm. What your use case? The thing is that it's not really specified if this callback is supposed to be triggered before or after a point is added, so changing this behavior might result in other people creating bugs that says the exact opposite ;)

**Comment by pbcomm** [comment]
This is how it was behaving in previous version. In my case, the signature box is transparent so it shows the placeholder `Please sign here` text under it. After user clicks/touches signature box I check if its empty and then change the background to white which hides the placeholder text behind it.

Example:
```
        let ctx = signatureCanvas.getContext('2d');
        if (signaturePad.isEmpty()) {
          ctx.fillStyle = 'rgb(255, 255, 255)';
          ctx.fillRect(0, 0, signatureCanvas.width, signatureCanvas.height);
        }
```

Maybe you can suggest something else.

**Comment by szimek** [comment]
Thanks for providing a use case. I'll think if it makes sense to change it for 3.0, which should be released soon-ish. It's really easy to change - just move [this](https://github.com/szimek/signature_pad/blob/master/src/signature_pad.ts#L255-L257) code 3 lines up ;)

While somewhat hacky, instead of using `isEmpty()` you could use `toData()` and check if there's just one point group with one point in it - if there's just one, it means that they've just started drawing.

BTW. In which version has it behaved differently?

**Comment by pbcomm** [comment]
I'm currently using 2.3.0

**Comment by UziTech** [comment]
closing as stale
