### ISSUE TITLE
Incorrect mouse drawing position after resizing

### ISSUE THREAD

**Issue by madmiki80** [szimek/signature_pad#476]
I resized canvas manually in my window to test responsiveness and after that the position of the drawing in the canvas is misplaced. I draw a line and it's not where my mouse pointer is.

How can I fix it?

I am embedding it in a small angular app. 
All other features are ok ad I can save image and clear canvas.

Tested on chrome and firefox.

![position](https://user-images.githubusercontent.com/19203476/78798407-3d258080-79b9-11ea-98a0-7c3b74151121.png)

**Comment by iSR5** [comment]
I've encountered this issue before, and the reason behind this behavior is because the event coordinates have been taken from `e.clientX` and `e.clientY` which returns the coordinates based on the viewport. 

Unlike the client X and Y, the offset X and Y would return the coordinates from inside the canvas, which would make things much easier to handle the canvas coordinates. and resizing the canvas would be much more handled correctly. 

For the time being, to work around this issue you will have to resize the canvas, then readjust its size again using the canvas offset width and height multiply it by the viewport aspect ratio. Surely, changing the size of the canvas dynamically would clear out the signature, so if you need to keep the signature, you will have to store its data before resizing, and then restore it after resizing. This would increase the size of the canvas workspace. 


Here is a quick  [jsFiddle](https://jsfiddle.net/iSR5/tnb0hojy/10/) example

**Comment by YanYuanFE** [comment]
```
function resizeCanvas() {
        // When zoomed out to less than 100%, for some very strange reason,
        // some browsers report devicePixelRatio as less than 1
        // and only part of the canvas is cleared then.
        var context = canvas.getContext("2d"); //context.getImageData(0,0,canvas.width,canvas.height)
        var imgData = signaturePad ? signaturePad.toData() : null;
        var ratio =  Math.max(window.devicePixelRatio || 1, 1);
        canvas.width = canvas.offsetWidth * ratio;
        canvas.height = canvas.offsetHeight * ratio;
        context.scale(ratio, ratio);
        // context.putImageData(imgData,0,0);
        imgData && signaturePad.fromData(imgData);
    }
    
    window.onresize = resizeCanvas;
    resizeCanvas();
```

**Comment by eriktobben** [comment]
> I've encountered this issue before, and the reason behind this behavior is because the event coordinates have been taken from `e.clientX` and `e.clientY` which returns the coordinates based on the viewport. so, if you change an element inside a viewport, this would causes some incorrect coordinates and it won't be recalculated until the viewport changes. In other word, the signature pad has been designed to get the dimensions from the viewport only and its settings intent it to initialized once. That's why the signature works very flawlessly when first initialized.
> 
> To make it more open to dynamic changes, it has to depend on `e.offsetX, e.offsetY`. Unlike the client X and Y, the offset X and Y would return the coordinates from inside the canvas, which would make things much easier to handle the canvas coordinates. and resizing the canvas would be much more handled correctly.
> 
> For the time being, to work around this issue you will have to adjust the `resizeCanvas` function to get the size explicitly (code below). Surely, changing the size of the canvas dynamically would clear out the signature, so if you need to keep the signature, you will have to store its data before resizing, and then restore it after resizing. This would increase the size of the canvas workspace.
> 
> so the original canvas resizing function would be readjusted like this :
> 
> ```
>   var ratio = Math.max(window.devicePixelRatio || 1, 1);
>   canvas.width = width * ratio;
>   canvas.height = height * ratio;
>   canvas.getContext("2d").scale(ratio , ratio);
> ```
> 
> here you're resetting the canvas size explicitly, while the old function uses the canvas's offset. Now, if you need to keep your signature intact while resizing, you can do this :
> 
> ```
> // save current signature 
> var saveSignature = signature.toData(); 
> 
> //resizeCanvas();
> 
> //restore the signature 
> signature.fromData(saveSignature);
> ```
> 
> Here is a [jsFiddle](https://jsfiddle.net/iSR5/tnb0hojy/10/) example

Hi! I am having the same issues, and tried your code. It works in terms of drawing where the mouse is, but I get the following error in the console:

Uncaught ReferenceError: width is not defined
    at resizeCanvas (signature:1894)
    at signature:1901

I see that you changed `canvas.offsetWidth` to `width`. Where is the `width` defined?
