### ISSUE TITLE
signature pad won't display signature if hidden on initial page load, then revealed by jQuery slideDown

### ISSUE THREAD

**Issue by wmalexander** [szimek/signature_pad#485]
The form with the signature pad is hidden on page load, later revealed with jQuery slideDown. When this is in effect, no signature works on the pad. When "display: none" is removed from the form for the initial page load, all works as expected. Here's a demo:

[https://www.loom.com/share/8865cf1cc93145f1ac017ae1915edd69](https://www.loom.com/share/8865cf1cc93145f1ac017ae1915edd69)

No console errors. What am I doing wrong?

**Comment by chatzikk** [comment]
Is there any solution for this issue as I have the same problem?

**Comment by lexandclo** [comment]
Same here, if i only dev console on browser and close again it works fine, but not on page load

**Comment by adsheff** [comment]
There are a few issues with it when it is hidden and shown. One solution is to call $(window).resize(); after the slideDown - which reinitialises the signature Pad. Don't really know the ins and outs but this works for me.

**Comment by sofiiahitlan** [comment]
Another option Instead of using `display: none;` you could position your form way off the screen (-5000px). When ready to display it, change the margin to the positive value. 
CSS manipulations didn't work for me. Instead of playing with CSS, I didn't render the signature pad until the user was ready to sign. I.e. wrap the signature pad component with the condition that listens to some event.

**Comment by dennisMeeQ** [comment]
Had the same issue. The problem was that the container displaying the signature pad was hidden with `display: none` while the signature pad was rendering. My (hacky) solution was to wait until the container was rendered and only then render the signature pad.

**Comment by UziTech** [comment]
closing as stale

**Comment by Vladimir-Romanets** [comment]
The problem is we need to reinitialise canvas with some value when it shown in our DOM. So we need do next:
1. Detect if the canvas visible (not mounted).
2. Run reinitialising canvas process if it became visible.

So, here is my solution:

1. I use hook to detect if element visible (https://stackoverflow.com/questions/45514676/react-check-if-element-is-visible-in-dom, thankfully **GuCier**)

```
function useOnScreen(ref: React.MutableRefObject<HTMLCanvasElement>) {
  const [isIntersecting, setIntersecting] = useState(false);

  const observer = useMemo(
    () =>
      new IntersectionObserver(([entry]) =>
        setIntersecting(entry.isIntersecting)
      ),
    []
  );

  useEffect(() => {
    observer.observe(ref.current);

    return observer.disconnect;
  }, []);

  return isIntersecting;
}
```

2. Run reinitialising canvas process for SignaturePad component:
```
    ...
   const isVisible = useOnScreen(canvasRef);
   ....
   useEffect(() => {
      if (isVisible) {
        resizeCanvas(canvasRef.current, signaturePadInstance);
      }
   }, [isVisible]);
   ...
