### ISSUE TITLE
Clear-Button throws exception

### ISSUE THREAD

**Issue by jona-es** [szimek/signature_pad#654]
First of all, thanks for signature_pad which is quite useful.
Well I have a problem which I posted here: https://jsfiddle.net/ang7c1mr/

I use bootstrap 5. Inside my form I use isgnature_pad, but as I press clear button, my php is called (this shouldn't be done).
By debugging I can see that jquery throws an exception which is passed to some bootsrap wrapper js.

I guess it's my fault, but I've already tried to change the script position (inside, outside form, plain, in js file, etc) and in the end I don't get it, so hopefully you could kindly help me, and this post could help some more fellows.

**Comment by UziTech** [comment]
Your clear button is in a `<form>` element which makes it a "Submit" type button by default so it will submit the form when pressed. You can change the button [type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type) by adding `type="button"` to the element.

Since this type of question doesn't really have to do with signature_pad it would be better asked on stackoverflow or somewhere for general html programming questions.
