### ISSUE TITLE
Problems with iOS8

### ISSUE THREAD

**Issue by monkeypetteri** [szimek/signature_pad#73]
First of all, thanks for a great component! It's nice, configurable and beautiful. It's worked on our web/iPad project nicely.. until iOS8. We encounter a problem, when the signature is at the bottom of a long page. If you sign first, then scroll up (so that the signature disappears), and scroll back down, the signature is gone. Same happens even on your GitHub demo if the device orientation changes. It also happens on the GitHub demo when I resize the browser window on Chrome. 

Even yet, as the clearing of signature happens unintended, we cannot use the library functions to get information if the signature is there or not.. So it's at the moment unusable, if we want to verify that a signature is entered. Any tips or possible fixes for this?

**Comment by alexcroox** [comment]
For anyone else looking to solve this, this was my final solution for iOS responsive scrolling fix (edited heavily to simply for procedural example)

```
var sig = new SignaturePad($('.sig').get(0));

$(window).on('resize', function() {
        
    resizeCanvas($('.sig').get(0), sig);
 });

resizeCanvas($('.sig').get(0), sig);

function resizeCanvas(context, sigElement) {

    var sigData = sigElement.toDataURL();

    var ratio =  Math.max(window.devicePixelRatio || 1, 1);
    context.width = context.offsetWidth * ratio;
    context.height = context.offsetHeight * ratio;
    context.getContext("2d").scale(ratio, ratio);

    sigElement.fromDataURL(sigData);
}
```

**Comment by vonsky104** [comment]
Hello, I know it's been a lot of time since last comment, but I started using Signature Pad (which is awesome btw) and had same problem with mobiles, when I scroll top or change orientation signature disappeared. I changed function in app and it started to work properly, here's my solution: 
from: `window.onresize = resizeCanvas;` I went to 
` window.onorientationchange = function() {
    var data = signaturePad.toData();
    resizeCanvas();
    signaturePad.fromData(data);
  }`
It just takes actual signature and store it in data var which reappears after orientation change. Hope it helps you, cheers :)
