### ISSUE TITLE
Can fromDataURL and erase be used together?

### ISSUE THREAD

**Issue by smalljop** [szimek/signature_pad#775]
Can fromDataURL and erase be used together? Set compositeOperation to destination-out for erasing. After erasing, white lines will appear on the background image. How can I solve this problem? Thank you

**Comment by smalljop** [comment]
![image](https://github.com/szimek/signature_pad/assets/17917807/9a0342f9-459f-4447-b546-db7f29882df7)

**Comment by UziTech** [comment]
Unfortunately html canvas doesn't have a concept of layers. So your background image could be drawn just like the signature and it wouldn't know the difference. In other words erasing will erase everything regardless of whether it is an image or not. And there is nothing we can do in signature_pad to change that.

One thing you can do is instead of adding the image to the canvas make the canvas background transparent and put the image behind it with position absolute or some other css.

**Comment by smalljop** [comment]
Thanks for your reply. If I set the image as the unit's label, then toDataURL will only have manually drawn content. If I want to get the image including the background, how can I do it?

**Comment by UziTech** [comment]
Once you have the final signature you can create a new canvas with the image and signature and get the full image that way

**Comment by smalljop** [comment]
Got it. Thank you.

**Comment by smalljop** [comment]
6
